server:
 port: 8081

spring:
 datasource:
  url: jdbc:h2:mem:identity_db
  username: sa 
  password:
  driver-class-name: org.h2.Driver
 jpa:
  show-sql: true

management:
 endpoints:
  web:
   exposure:
     include: health,info,metrics,prometheus
 endpoint:
  health:
   show-details: always
 data:
  redis:
   host: docker
   port: 6379 
 tracing:
  sampling:
    probability: 1.0
